
services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: utec
      POSTGRES_DB: gestion_usuarios
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Montar el script SQL para inicializar la base de datos
    networks:
      - app-network

  api:
    build: .
    container_name: fastapi_app
    environment:
      DB_HOST: 34.195.53.21  # IP externa de la base de datos
      DB_USER: postgres
      DB_PASSWORD: utec
      DB_NAME: gestion_usuarios
    ports:
      - "3001:8000"  # Exponer el puerto 8000 dentro del contenedor como 3001 externamente
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
